formats:
  - oas3
extends:
  - spectral:oas
rules:
  camara-version:
    description: Version must be MAJOR.MINOR.PATCH Adding -rc and -wip as valid suffixes though we should add these to the commonalities if we continue to use them
    severity: error
    recommended: true
    message: "{{property}} is not MAJOR.MINOR.PATCH: {{error}}"
    given: $.info.version
    then:
      function: pattern
      functionOptions:
        match: ^[0-9]+\.[0-9]+\.[0-9]+(?:-rc|-wip)?$
