formats:
  - oas3
extends:
  - spectral:oas
camel-case-name:
  description: Name should be camelCased.
  given: "$.paths.*.*.operationId"
  then:
    function: casing
    functionOptions:
      type: camel
