functions:
  - check-for-reserved-words
functionsDir: "./lint_function"
rules:
  check-reserved-words-in-paths:
    message: "Reserved words found in path key: {{error}}"
    severity: warn
    given: "$.paths.*.*"
    then:
      function: check-for-reserved-words
