functions:
  - camara-language-avoid-telco
  - camara-oas-version
  - camara-reserved-words
  - camara-security-no-secrets-in-path-or-query-parameters
functionsDir: "./lint_function" 
rules:
  check-telco-specific-terms:
    message: "{{error}}"
    severity: hint
    description: |
      This rule checks for telco-specific terminology in your API definitions and suggests more inclusive terms.
    given: "$..*.*"
    then:
      function: camara-language-avoid-telco
  camel-case-name:
    message: Operation Id must be in Camel case "{{error}}"
    severity: hint
    description: |
        This rule checks Operation ids should follow a specific case convention: camel case.
    given: "$.paths.*.*.operationId"
    then:
      function: casing
      functionOptions:
        type: camel
  paths-kebab-case:
    description: Paths should be kebab-case.
    message: "{{property}} should be kebab-case (lower-case and separated with hyphens)"
    severity: warn
    given: $.paths[*]~
    then:
      function: pattern
      functionOptions:
        match: "^(\/|[a-z0-9-.]+|{[a-zA-Z0-9_]+})+$"
  check-sensitive-data-in-paths:
    message: "Sensitive data found in path: {{error}}"
    severity: warn
    description: |
      This rule checks for sensitive data ('MSISDN' and 'IMSI') in API paths and suggests avoiding their use.
    given: 
      - "$.paths"
    then:
      function: camara-security-no-secrets-in-path-or-query-parameters
  check-reserved-words-in-paths:
    message: "Reserved words found in path key: {{error}}"
    severity: warn
    description: |
      This rule checks Reserved words must not be used in the following parts of an API specification [Paths, Request Body properties, Component, Operation Id, Security Schema]
    given: 
       - "$.paths"
       - "$.components.schemas.*.properties"
       - "$.components.securitySchemes"
       - "$.components"
       - "$.paths.*.*.operationId"
    then:
      function: camara-reserved-words
  camara-parameters-descriptions:
    description: This spectral rules check for the description of each parameter
    message: Parameter must have description "{{error}}"
    severity: hint
    given: 
       - "$.components.*.*"
       - "$.components.*.*.properties.*"
    then:
      field: description
      function: truthy
  camara-operation-summary:
    message: Summary must be defined on each operation, describing with a short summary what the operation does.
    severity: warn
    given: "$.paths.*."
    then:
      field: summary 
      function: truthy   
  check-openapi-version:
    message: "OpenAPI version issue: {{error}}"
    severity: warn
    description: |
      This rule checks if the OpenAPI version is 3.0.3.
    given:
      - "$.openapi"
    then:
      function: camara-oas-version      
