rules:
  camara-parameters-descriptions:
    description: This spectral rules check for the description of each parameter
    message: Parameter must have description "{{error}}"
    severity: hint
    given: "$.components.schemas.*.properties"
    then:
      field: description
      function: truthy
