rules:
  check-reserved-words:
    message: "{{error}}"
    severity: warn
    given: "$.paths.*.* | $.components.schemas.* | $.components.responses.*"
    then:
      function: camara-reserved-words
