rules:
  important-fields:
    description: Absolutely must have a title and a description
    message: "Missing the description {{property}}"
    severity: hint
  given: "$.info"
  then:
    - field: "description"
      function: truthy
