functions:
  - camara-reserved-words
  - camara-oas-version
functionsDir: "./lint_function"
rules:
  check-reserved-words-in-paths:
    message: "Reserved words found in path key: {{error}}"
    severity: warn
    description: |
      This rule checks Reserved words must not be used in the following parts of an API specification [Paths, Request Body properties, Component, Operation Id, Security Schema]
    given:
      - "$.paths"
      - "$.components.schemas.*.properties"
      - "$.components.securitySchemes"
      - "$.components"
      - "$.paths.*.*.operationId"
    then:
      function: camara-reserved-words
      
