functions:
  - check-spelling-code
  - check-telco-specific-terms
functionsDir: "./lint_function"
rules:
  language-spelling-texts:
    message: "{{error}}"
    severity: warn
    given:
      - "$.info.title"
      - "$.info.summary"
      - "$.info.description"
      - "$.paths.*.*.parameters[?(@.in==='query' || @.in==='path' || @.in==='cookie')].description"
      - "$..properties.*.description"
    then:
      function: check-spelling-code
  reduce-telco-specific-terminology:
    message: "{{error}}"
    severity: warn
    description: |
      This rule checks for telco-specific terminology in your API definitions and suggests more inclusive terms.
    given: "$.**"
    then:
      function: check-telco-specific-terms
