functions:
  - camara-oas-version
functionsDir: "./lint_function"
rules:
  check-openapi-version:
    message: "OpenAPI version issue: {{error}}"
    description: |
      This rule checks if the OpenAPI version is 3.0.3.
    given:
      - "$.openapi"
    then:
      function: camara-oas-version
    severity: error
