rules:
  important-fields:
    description: Absolutely must have a title and a description
    message: "Missing the {{property}}"
  given: "- "$.info"
  then:
    - field: "title"
      function: truthy

    - field: "description"
      function: truthy
