functions:
  - camara-reserved-words
functionsDir: "./lint_function"
rules:
  check-reserved-words-in-paths:
    message: "Reserved words found in path key: {{error}}"
    severity: warn
    given: 
       - "$.paths"
       - "$.components.schemas.*.properties"
    then:
      function: camara-reserved-words
