extends: [[spectral:oas, off]]
functions:
  - camara-reserved-words
functionsDir: "./lint_function"
rules:
  #  Built-in OpenAPI Specification ruleset. Each rule then can be enabled individually.
  #  The severity keyword is optional in rule definition and can be error, warn, info, hint, or off. The default value is warn. 
  contact-properties: true
  duplicated-entry-in-enum: true
  info-contact: true
  info-description: true
  info-license: true
  license-url: true
  no-$ref-siblings: error
  no-eval-in-markdown: true
  no-script-tags-in-markdown: true
  openapi-tags: false
  openapi-tags-alphabetical: false
  openapi-tags-uniqueness: error
  operation-description: true
  operation-operationId: true
  operation-operationId-unique: error
  operation-operationId-valid-in-url: true
  operation-parameters: true
  operation-singular-tag: true
  operation-success-response: true
  operation-tags: true
  operation-tag-defined: true
  path-declarations-must-exist: true
  path-keys-no-trailing-slash: true
  path-not-include-query: true
  path-params: false
  tag-description: false
  typed-enum: true
  oas3-api-servers: true
  oas3-examples-value-or-externalValue: true
  oas3-operation-security-defined: true
  oas3-parameter-description: false
  oas3-schema: true
  oas3-server-not-example.com: true
  oas3-server-trailing-slash: true
  oas3-unused-component: true
  oas3-valid-media-example: true
  oas3-valid-schema-example: true
  oas3-server-variables: true
  
  # Custome rules
  check-sensitive-data-in-paths-and-query-params:
    message: "Sensitive data found in path or query parameters: {{error}}"
    severity: warn
    given:
      - "$..parameters[?(@ && @.in && @.in.match(/path/))].name"
      - "$..parameters[?(@ && @.in && @.in.match(/query/))].name"
    then:
      function: pattern
      functionOptions:
        notMatch: /^(client_secret|token|access_token|refresh_token|id_token|password|secret|apikey|MSISDN)$/i
        
  check-reserved-words-in-paths:
    message: "Reserved words found in path key: {{error}}"
    severity: warn
    description: |
      This rule checks Reserved words must not be used in the following parts of an API specification [Paths, Request Body properties, Component, Operation Id, Security Schema]
    given: 
       - "$.paths"
       - "$.components.schemas.*.properties"
       - "$.components.securitySchemes"
       - "$.components"
       - "$.paths.*.*.operationId"
    then:
      function: camara-reserved-words
      
  camara-parameters-descriptions:
    message: "Parameter description is missing or empty: {{error}}"
    severity: hint
    description: |
      This Spectral rule ensures that each parameter in the API specification, including components and properties, has a descriptive and meaningful description.
    given:
      - "$.components.*.*"
      - "$.components.*.*.properties.*"
    then:
      field: description
      function: truthy
      
  camara-operation-summary:
    message: "Operation Summary Warning: Each operation should include a short summary for better understanding."
    severity: warn
    description: |
            This rule checks if each operation (POST, GET, DELETE, PUT, PATCH, OPTIONS) in your API specification has a meaningful summary. 
            Ensure that you have added a 'summary' field for each operation in your OpenAPI specification.
    given:
      - "$.paths.*.post"
      - "$.paths.*.get"
      - "$.paths.*.delete"
      - "$.paths.*.put"
      - "$.paths.*.patch"
      - "$.paths.*.options"
    then:
      field: summary
      function: truthy
      
  camara-path-param-id:
    message: "Path Parameter Naming Warning: Use 'resource_id' instead of just 'id' in path parameters."
    severity: warn
    description: |
      This rule ensures consistent and descriptive naming for path parameters in your OpenAPI specification. 
      Please use 'resource_id' instead of just 'id' for your path parameters.
    given: "$..parameters[?(@.in == 'path')]"
    then:
      field: name
      function: pattern
      functionOptions:
        notMatch: \b(id|Id|ID|iD)\b
        
  check-openapi-version:
    message: "OpenAPI Version Error: The OpenAPI specification must adhere to version 3.0.3."
    severity: error
    description: |
      This rule validates the OpenAPI version in your specification and requires compliance with version 3.0.3.
    given: "$"
    then:
      field: openapi
      function: pattern
      functionOptions:
        match: 3.0.3
