extends: [[spectral:oas, all]]
rules:
  contact-properties: false
  duplicated-entry-in-enum: true
  info-contact: true
  info-description: true
  info-license: true
  license-url: true
  no-$ref-siblings: error
  no-eval-in-markdown: true
  no-script-tags-in-markdown: true
  openapi-tags: false
  openapi-tags-alphabetical: false
  openapi-tags-uniqueness: error
  operation-description: true
  operation-operationId: true
  operation-operationId-unique: error
  operation-operationId-valid-in-url: true
  operation-parameters: true
  operation-singular-tag: true
  operation-success-response: true
  operation-tags: true
  operation-tag-defined: true
  path-declarations-must-exist: true
  path-keys-no-trailing-slash: true
  path-not-include-query: true
  path-params: error
  tag-description: false
  typed-enum: true
  oas3-api-servers: true
  oas3-examples-value-or-externalValue: true
  oas3-operation-security-defined: true
  oas3-parameter-description: false
  oas3-schema: true
  oas3-server-not-example.com: true
  oas3-server-trailing-slash: true
  oas3-unused-component: true
  oas3-valid-media-example: true
  oas3-valid-schema-example: true
  oas3-server-variables: true
