functions:
  - check-reserved-words
functionsDir: "./lint_function"
rules:
  check-reserved-words:
    message: "{{error}}"
    severity: warn
    given:  "$.paths.*"
    then:
      function: check-reserved-words
