extends:
  - ./spectral-oas.yml
rules:
  camel-case-name:
  description:  This rule checks Operation ids should follow a specific case convention: camel case.
  given: "$.paths.*.*.operationId"
  then:
    function: casing
    functionOptions:
      type: camel
