functions:
  - camara-reserved-words
functionsDir: "./lint_function"
rules:
  check-reserved-words-in-paths:
    message: "Reserved words found in path key: {{error}}"
    severity: warn
    given: 
      - "$.paths.*.*.parameters[?(@.in==='query' || @.in==='path' || @.in==='cookie')].description"
      - "$..properties.*.description"
    then:
      function: camara-reserved-words
