functions:
  - camara-parameters-descriptions
functionsDir: "./lint_function"
rules:
  check-parameter-descriptions:
    message: "Parameter description issue: {{error}}"
    description: |
      This rule checks if all parameters have descriptions.
    given:
      - "$.info"
    then:
      function: check-parameter-descriptions
    severity: warn
