functions:
  - check-spelling-code
  - check-telco-specific-terms
  - check-path-parameters
functionsDir: "./lint_function"
rules:
  check-spelling-code:
    message: "{{error}}"
    severity: warn
    given:
      - "$.info.title"
      - "$.info.summary"
      - "$.info.description"
      - "$.paths.*.*.parameters[?(@.in==='query' || @.in==='path' || @.in==='cookie')].description"
      - "$..properties.*.description"
    then:
      function: check-spelling-code
  check-telco-specific-terms:
    message: "{{error}}"
    severity: hint
    description: |
      This rule checks for telco-specific terminology in your API definitions and suggests more inclusive terms.
    given: "$..*.*"
    then:
      function: check-telco-specific-terms
  camara-path-param-id:
    message: "{{error}}"
    severity: warn
    description: |
      Path parameters must be self-identifying. It is not enough with 'id'.
    given: "$.paths.*.*.parameters"
    then:
      function: check-path-parameters
  camara-path-param-id-morphology:
    message: "{{error}}"
    severity: warn
    description: |
      Path parameter identifiers should have a similar morphology on all endpoints.
    given: "$.paths.*.*.parameters"
    then:
      function: check-path-parameters
