functions:
  - camara-language-avoid-telco
  - camara-oas-version  
functionsDir: "./lint_function" 
rules:
  check-telco-specific-terms:
    message: "{{error}}"
    severity: hint
    description: |
      This rule checks for telco-specific terminology in your API definitions and suggests more inclusive terms.
    given: "$..*.*"
    then:
      function: camara-language-avoid-telco
  camel-case-name:
    message: Operation Id must be in Camel case "{{error}}"
    severity: hint
    description: |
        This rule checks Operation ids should follow a specific case convention: camel case.
    given: "$.paths.*.*.operationId"
    then:
      function: casing
      functionOptions:
        type: camel
  paths-kebab-case:
    description: Paths should be kebab-case.
    message: "{{property}} should be kebab-case (lower-case and separated with hyphens)"
    severity: warn
    given: $.paths[*]~
    then:
      function: pattern
      functionOptions:
        match: "^(\/|[a-z0-9-.]+|{[a-zA-Z0-9_]+})+$"      
  check-openapi-version:
    message: "OpenAPI version issue: {{error}}"
    severity: warn
    description: |
      This rule checks if the OpenAPI version is 3.0.3.
    given:
      - "$.openapi"
    then:
      function: camara-oas-version      
