functions:
  - spectral:oas
rules:
  check-camel-case-properties:
    description: Check for camel case property names
    message: Property '{{key}}' should be in camelCase.
    given: "$.paths.*.*.operationId"
    then:
      function: spectral:oas
      functionOptions:
        rules:
          camelCase: true
    severity: error
