functions:
  - camara-reserved-words
functionsDir: "./lint_function"
rules:
  check-sensitive-data-in-paths-and-query-params:
    message: "Sensitive data found in path or query parameters: {{error}}"
    severity: error
    description: |
    This rule checks for sensitive data ('client_secret', 'token', 'access_token', 'refresh_token', 'id_token', 'password', 'secret', 'apikey', 'MSISDN') in API paths and query parameters, and recommends passing such information in headers instead.
    given:
      - "$..parameters[?(@.in == 'path' && (@.name =~ /^(client_secret|token|access_token|refresh_token|id_token|password|secret|apikey|MSISDN)$/i || @.description =~ /^(client_secret|token|access_token|refresh_token|id_token|password|secret|apikey|MSISDN)$/i))].name"
      - "$..parameters[?(@.in == 'query' && (@.name =~ /^(client_secret|token|access_token|refresh_token|id_token|password|secret|apikey|MSISDN)$/i || @.description =~ /^(client_secret|token|access_token|refresh_token|id_token|password|secret|apikey|MSISDN)$/i))].name"
    then:
      field: name
      function: pattern
      functionOptions:
        match: /^(client_secret|token|access_token|refresh_token|id_token|password|secret|apikey|MSISDN)$/i
  check-reserved-words-in-paths:
    message: "Reserved words found in path key: {{error}}"
    severity: warn
    description: |
      This rule checks Reserved words must not be used in the following parts of an API specification [Paths, Request Body properties, Component, Operation Id, Security Schema]
    given:
      - "$.paths"
      - "$.components.schemas.*.properties"
      - "$.components.securitySchemes"
      - "$.components"
      - "$.paths.*.*.operationId"
    then:
      function: camara-reserved-words
  camara-parameters-descriptions:
    description: This spectral rules check for the description of each parameter
    message: Parameter must have description "{{error}}"
    severity: hint
    given:
      - "$.components.*.*"
      - "$.components.*.*.properties.*"
    then:
      field: description
      function: truthy
  camara-operation-summary:
    message: "Operation Summary Warning: Each operation should include a short summary for better understanding."
    severity: warn
    description: |
            This rule checks if each operation (POST, GET, DELETE, PUT, PATCH, OPTIONS) in your API specification has a meaningful summary. 
            Ensure that you have added a 'summary' field for each operation in your OpenAPI specification.
    given:
      - "$.paths.*.post"
      - "$.paths.*.get"
      - "$.paths.*.delete"
      - "$.paths.*.put"
      - "$.paths.*.patch"
      - "$.paths.*.options"
    then:
      field: summary
      function: truthy    
  camara-path-param-id:
    message: "Path Parameter Naming Warning: Use 'resource_id' instead of just 'id' in path parameters."
    severity: warn
    description: |
      This rule ensures consistent and descriptive naming for path parameters in your OpenAPI specification. 
      Please use 'resource_id' instead of just 'id' for your path parameters.
    given: "$..parameters[?(@.in == 'path')]"
    then:
      field: name
      function: pattern
      functionOptions:
        notMatch: \b(id|Id|ID|iD)\b    
  check-openapi-version:
    message: "OpenAPI Version Error: The OpenAPI specification must adhere to version 3.0.3."
    severity: error
    description: |
      This rule validates the OpenAPI version in your specification and requires compliance with version 3.0.3.
    given: "$"
    then:
      field: openapi
      function: pattern
      functionOptions:
        match: 3.0.3
