functions:
  - findSpellingMistakesInFile
  rules:
  language-spelling-names:
    message: "{{error}}"
    severity: warn
    given:
      - "$.paths.*~"
      - "$.paths.*.*.parameters[?(@.in==='query' || @.in==='path' || @.in==='cookie')].name"
      - "$..properties.*~"
    then:
      function: findSpellingMistakesInFile
extends:
  - "spectral:oas"
