functions:
  - camara-reserved-words
functionsDir: "./lint_function"
rules:
  check-reserved-words:
    message: "{{error}}"
    severity: warn
    given: "$..*.*"
    then:
      function: camara-reserved-words
