rules:
  camara-parameters-descriptions:
    description: This spectral rules check for the description of ecah parameter
    message: Parameter must have description "{{error}}"
    severity: hint
    given: $.components"[*]
    then:
      field: description
      function: truthy
