parserOptions:
  duplicateKeys: warn # error is the default value
  incompatibleValues: off # error is the default value
rules:
  camara-parameters-descriptions:
    description: This spectral rules check for the description of ecah parameter
    message: Parameter must have description "{{error}}"
    severity: hint
    given: "$.components.schemas.*.properties"
    then:
      field: description
      function: truthy
