openapi: 3.0.3
info:
  title: Sample API
  version: 1.0.0

paths:
  /users/{userId}:
    get:
      summary: Get User by ID
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
          description: User ID
      responses:
        '200':
          description: Successful response
