openapi: 3.0.3
info:
  title: Sample API
  version: 1.0.0

paths:
  /switch/{switchId}:
    get:
      summary: Get import by ID
      parameters:
        - name: importId
          in: path
          required: true
          schema:
            type: string
          description: switch ID
      responses:
        '200':
          description: Successful response
