openapi: 3.0.3
info:
  title: Sample API
  version: 1.0.0

paths:
  /Hello/{hello_id}:
    get:
      summary: Get Hello Message by ID
      description: Returns a hello message based on the provided ID.
      parameters:
        - name: hello_id
          in: path
          required: true
          schema:
            type: string
          description: This should ideally be named 'resource_id' for consistency.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                message: Hello, World!

  /Hello/{resource_id}:
    get:
      summary: Get Hello Message by Resource ID
      description: Returns a hello message based on the provided resource ID.
      parameters:
        - name: resource_id
          in: path
          required: true
          schema:
            type: string
          description: Consistently named path parameter.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                message: Hello, World!
